#pragma once
// G7: Layer-3 ASIC energy/area/freq projection. Takes a workload summary
// (OpCounters + cycles + memory hierarchy stats) and projects per-token
// energy, perf/W, area, and frequency on three target tech nodes (22nm,
// 7nm, 3nm). Tech-node scaling follows Stillmaker-Baas 2017 (Dennard
// scaling broken post-28nm; 3nm is documented extrapolation). Per-op
// energy baselines follow Horowitz 2014 (ISSCC keynote, Table 1) and the
// ternary-vs-binary reduction follows Cuevas 2026 Proposition 2
// (switching activity ratio log2(3)/log2(2) ≈ 1.585; ternary energy ≈
// 1/1.585 ≈ 63% of an equivalent binary baseline).
#include <ter/counters.hpp>
#include <tersim/cache_model.hpp>
#include <cstdint>

namespace tersim {

enum class TechNode { N22nm, N7nm, N3nm };

// Per-op picojoule cost @ the configured tech node, plus per-byte memory
// costs and leakage parameters. Defaults are populated for 22nm by
// AsicModel::defaults_for(); scaling to 7nm/3nm is applied at projection
// time using the published Stillmaker-Baas 2017 factors.
struct AsicConfig {
    TechNode node = TechNode::N22nm;

    // Compute energy (pJ per op invocation) — Horowitz 2014 Tab.1 @45nm
    // rescaled to 22nm (~0.5×) and trit-aware via Cuevas Prop.2.
    double pj_tadd     = 0.030;    // INT8-equivalent add @22nm
    double pj_tsub     = 0.030;
    double pj_tneg     = 0.015;
    double pj_tabs     = 0.015;
    double pj_tlogic3  = 0.020;    // TAND3/TOR3/TXOR3 (3-state logic)
    double pj_tcmp     = 0.025;
    double pj_tsign    = 0.015;
    double pj_tloadi   = 0.010;
    double pj_tbranch  = 0.040;    // TBEQ/TBNE/TBLT/TJUMP/TCALL/TRET
    double pj_tcontrol = 0.005;    // TNOP/THALT/TDBG
    double pj_tvadd    = 0.060;    // 9-trit vector add (~2× scalar)
    double pj_tvsub    = 0.060;
    double pj_tvneg    = 0.030;
    double pj_tvmul    = 0.300;    // 9-trit element-wise mul
    double pj_tvmac    = 0.180;    // 9-trit MAC; ternary mul collapses to add/sub/skip
    double pj_tvsum    = 0.090;    // 9-trit reduction
    double pj_tvmax    = 0.090;
    double pj_tvshuf   = 0.040;
    double pj_tvbcast  = 0.020;

    // Memory energy (pJ per access at each level). Horowitz 2014: ~0.5 pJ
    // for an SRAM read @22nm scaled; DRAM ~1300 pJ/byte (HBM lower but we
    // model commodity DDR target).
    double pj_l1_access   = 5.0;       // ~64B line, per access (load or store)
    double pj_l2_access   = 50.0;
    double pj_dram_access = 1300.0;    // per access (treat as ~1 cache line)

    // Frequency (GHz) — typical critical path: 0.8ns @22nm typical RTL.
    double freq_ghz = 1.25;            // 1/0.8ns

    // Area model: kilo-gate-equivalents per unit (kGE), one gate ≈ NAND2.
    // Scaled to mm² via process-density factor.
    double kge_alu      = 25.0;    // scalar trit ALU
    double kge_vec_unit = 220.0;   // 9-lane vector + accumulator
    double kge_l1d      = 800.0;   // 32 KB SRAM-equivalent gates
    double kge_l2       = 8000.0;  // 512 KB
    double kge_ctrl     = 50.0;    // fetch/decode/dispatch/regfile

    // mm² per kGE @22nm (≈ 1.2 µm² per gate). Scaled by node.
    double mm2_per_kge_22nm = 1.2e-3;

    // Leakage: static power density (W/mm²) @22nm; multiplied by area
    // and wall-time to derive leakage energy. Drops with node but slower
    // than active energy (Dennard broken).
    double leakage_w_per_mm2_22nm = 0.020;
};

struct AsicReport {
    double total_energy_pJ_per_token = 0.0;
    double perf_per_watt_tokps       = 0.0;
    double area_mm2                  = 0.0;
    double freq_GHz                  = 0.0;
    double wall_time_s_per_token     = 0.0;
    struct Breakdown {
        double compute_pJ = 0.0;
        double memory_pJ  = 0.0;
        double leakage_pJ = 0.0;
    } breakdown{};
};

// Aggregated workload summary the model consumes. Decoupled from any
// specific Sim/PipelineModel instance so callers can synthesize inputs.
struct AsicWorkload {
    const ter::OpCounters* counters = nullptr;    // required
    std::uint64_t          cycles_total   = 0;    // from PipelineReport
    std::uint64_t          l1d_accesses   = 0;
    std::uint64_t          l2_accesses    = 0;    // ≈ l1d misses
    std::uint64_t          dram_accesses  = 0;
    // Tokens generated by the workload (1 for a single-token forward).
    std::uint64_t          tokens         = 1;
};

class AsicModel {
public:
    explicit AsicModel(AsicConfig cfg = defaults_for(TechNode::N22nm)) noexcept
        : cfg_(cfg) {}

    AsicReport project(const AsicWorkload& w) const noexcept;

    // Builder for per-node defaults. Applies Stillmaker-Baas 2017 scaling
    // (active energy ~ 2× lower 22→7, ~1.6× lower 7→3; freq ~1.7× faster
    // 22→7, ~1.3× faster 7→3; leakage drops only ~1.4× per step).
    static AsicConfig defaults_for(TechNode node) noexcept;

    // Theoretical reduction of switching activity ternary vs binary
    // (Cuevas 2026 Prop 2). Exposed so tests can pin the constant.
    static constexpr double kCuevasTernaryRatio = 0.6309297535714574; // 1/log2(3)

    const AsicConfig& config() const noexcept { return cfg_; }

private:
    double compute_energy_pJ(const ter::OpCounters& c) const noexcept;
    double memory_energy_pJ(const AsicWorkload& w) const noexcept;
    double total_area_mm2()  const noexcept;

    AsicConfig cfg_;
};

}  // namespace tersim
